install.packages("statnet")
install.packages("igraph")
install.packages("latentnet")
install.packages("ggplot2")
install.packages("ggraph")
install.packages("netcoin")

install.packages("dplyr")
install.packages("ggrepel")
install.packages("lubridate")
install.packages("stringr")
install.packages("kableExtra")
install.packages("scales")
install.packages("knitr")